import os
import csv
import numpy as np
from PIL import Image
import pandas as pd


def _load_csv(filepath, delimiter=',', quotechar="'"):
    """
    Load a CSV file.

    Parameters
    ----------
    filepath : str
        Path to a CSV file
    delimiter : str, optional
    quotechar : str, optional

    Returns
    -------
    list of dicts : Each line of the CSV file is one element of the list.
    """
    data = []
    csv_dir = os.path.dirname(filepath)
    reader = csv.DictReader(open(filepath, 'r'), delimiter=delimiter,
                            quotechar=quotechar)
    for row in reader:
        if 'path' in row:
            row['path'] = os.path.abspath(os.path.join(csv_dir,
                                                       row['path']))
            data.append(row)
    return data


def generate_index(csv_filepath):
    """
    Generate an index 0...k for the k labels.

    Parameters
    ----------
    csv_filepath : str
        Path to 'test.csv' or 'train.csv'

    Returns
    -------
    dict : Maps a symbol_id as in test.csv and
        train.csv to an integer in 0...k, where k is the total
        number of unique labels.
    """
    symbol_id2index = {}
    data = _load_csv(csv_filepath)
    i = 0
    for item in data:
        if item['symbol_id'] not in symbol_id2index:
            symbol_id2index[item['symbol_id']] = i
            i += 1
    return symbol_id2index


def load_images(csv_filepath, symbol_id2index, one_hot=True, flatten=False,
                size=28):
    """
    Load the images into a 4D uint8 numpy array [index, y, x, depth].

    Parameters
    ----------
    csv_filepath : str
        'test.csv' or 'train.csv'
    symbol_id2index : dict
        Dictionary generated by generate_index
    one_hot : bool, optional
        Make label vector as 1-hot encoding, otherwise index
    flatten : bool, optional
        Flatten feature vector

    Returns
    -------
    images, labels : Images is a 4D uint8 numpy array [index, y, x, depth]
                     and labels is a 2D uint8 numpy array [index][1-hot enc].
    """
    WIDTH, HEIGHT = size, size
    dataset_path = os.path.dirname(csv_filepath)  # Main directory of HASY
    data = _load_csv(csv_filepath)
    if flatten:
        images = np.zeros((len(data), WIDTH * HEIGHT))
    else:
        images = np.zeros((len(data), WIDTH, HEIGHT))
    labels = []
    images = []
    for i, data_item in enumerate(data):
        fname = os.path.join(dataset_path, data_item['path'])
        if flatten:
            img = Image.open(fname)
            img = img.convert('L')
            img = img.resize((size, size))
            img = np.array(img)
            images.append(img)
        else:
            img = Image.open(fname)
            img = img.convert('L')
            img = img.resize((size, size))
            img = np.array(img)
            images.append(img)
        label = symbol_id2index[data_item['symbol_id']]
        labels.append(label)
    df = pd.DataFrame({'images': images, 'labels': labels})
    # shuffle the data
    df = df.sample(frac=1)
    x = np.array(list(df['images']))
    y = np.array(df['labels'])
    data = x, y
    if one_hot:
        data = (data[0], np.eye(len(symbol_id2index))[data[1]])
    return data
